Repository rockandror/consul, pull requests merged in 2019-09, with the labels that each got.

#44 Manage settings for old and new installations
  config/deploy.rb
  lib/tasks/settings.rake
Labels: Module 6

#43 Social network registration section
  app/assets/stylesheets/admin.scss
  app/controllers/admin/settings_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/helpers/settings_helper.rb
  app/models/setting.rb
  app/views/admin/settings/_mixed_settings_table.html.erb
  app/views/admin/settings/social.html.erb
  app/views/devise/_omniauth_form.html.erb
  app/views/shared/_social_media_meta_tags.html.erb
  config/i18n-tasks.yml
  config/initializers/devise.rb
  config/locales/ast/settings.yml
  config/locales/bs-BA/settings.yml
  config/locales/ca/settings.yml
  config/locales/cs-CZ/settings.yml
  config/locales/da-DK/settings.yml
  config/locales/de-DE/settings.yml
  config/locales/el-GR/settings.yml
  config/locales/en/admin.yml
  config/locales/en/settings.yml
  config/locales/es-PE/settings.yml
  config/locales/es/admin.yml
  config/locales/es/settings.yml
  config/locales/fa-IR/settings.yml
  config/locales/fi-FI/settings.yml
  config/locales/fr/settings.yml
  config/locales/gl/settings.yml
  config/locales/he/settings.yml
  config/locales/id-ID/settings.yml
  config/locales/it/settings.yml
  config/locales/nl/settings.yml
  config/locales/pl-PL/settings.yml
  config/locales/pt-BR/settings.yml
  config/locales/ru/settings.yml
  config/locales/sl-SI/settings.yml
  config/locales/so-SO/settings.yml
  config/locales/sq-AL/settings.yml
  config/locales/sv-SE/settings.yml
  config/locales/tr-TR/settings.yml
  config/locales/val/settings.yml
  config/locales/zh-CN/settings.yml
  config/locales/zh-TW/settings.yml
  lib/retrocompatibility.rb
  lib/tasks/settings.rake
  spec/features/admin/feature_flags_spec.rb
  spec/features/admin/settings_spec.rb
  spec/helpers/settings_helper_spec.rb
  spec/models/setting_spec.rb
Labels: Module 6, design

#45 Ciudades abiertas/map configuration section
  app/controllers/admin/settings_controller.rb
  app/helpers/map_locations_helper.rb
  app/models/setting.rb
  app/views/admin/settings/_map_form.html.erb
  config/locales/en/settings.yml
  config/locales/es/settings.yml
  spec/features/admin/settings_spec.rb
  spec/helpers/map_locations_helper_spec.rb
Labels: Module 6

#46 Ciudades abiertas/advanced configuration section
  app/controllers/admin/settings_controller.rb
  app/controllers/application_controller.rb
  app/helpers/settings_helper.rb
  app/models/setting.rb
  app/views/admin/settings/_mixed_settings_table.html.erb
  app/views/admin/settings/advanced.html.erb
  config/i18n-tasks.yml
  config/locales/en/admin.yml
  config/locales/en/settings.yml
  config/locales/es/admin.yml
  config/locales/es/settings.yml
  lib/tasks/settings.rake
  spec/features/admin/settings_spec.rb
Labels: Module 6

#47 Ciudades abiertas/smtp configuration section
  app/controllers/admin/settings_controller.rb
  app/helpers/settings_helper.rb
  app/mailers/application_mailer.rb
  app/mailers/devise_mailer.rb
  app/models/setting.rb
  app/views/admin/settings/smtp.html.erb
  config/environments/preproduction.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/locales/en/admin.yml
  config/locales/en/settings.yml
  config/locales/es/admin.yml
  config/locales/es/settings.yml
  lib/smtp_configuration.rb
  lib/tasks/settings.rake
  spec/features/admin/settings_spec.rb
  spec/helpers/settings_helper_spec.rb
  spec/lib/tasks/settings_spec.rb
  spec/models/setting_spec.rb
Labels: Module 6

#48 Ciudades abiertas/regional section
  app/controllers/admin/settings_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/regional_settings.rb
  app/helpers/settings_helper.rb
  app/models/setting.rb
  app/views/admin/settings/_mixed_settings_table.html.erb
  app/views/admin/settings/regional.html.erb
  config/application.rb
  config/i18n-tasks.yml
  config/locales/en/admin.yml
  config/locales/en/settings.yml
  config/locales/es/admin.yml
  config/locales/es/settings.yml
  lib/regional/locales.rb
  lib/regional/timezone.rb
  spec/features/admin/settings_spec.rb
  spec/features/localization_spec.rb
  spec/helpers/settings_helper_spec.rb
  spec/lib/regional/locales.rb
  spec/lib/regional/timezone.rb
  spec/models/setting_spec.rb
Labels: Module 6

#50 Remove old settings tabs code
  app/assets/javascripts/application.js
  app/assets/javascripts/settings.js.coffee
  app/views/admin/dashboard/actions/_default_actions.html.erb
  app/views/admin/settings/_settings_form.html.erb
  app/views/admin/settings/_settings_table.html.erb
Labels: Module 6

#53 Fix smtp configuration
  lib/smtp_configuration.rb
Labels: Module 6

#54 Fix scroll and active button
  app/assets/javascripts/foundation_extras.js
  app/views/admin/_menu.html.erb
Labels: design

#52 Ciudades abiertas/installation wizard
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/wizard.scss
  app/controllers/admin/settings_controller.rb
  app/controllers/admin/wizards/installer_controller.rb
  app/controllers/admin/wizards_controller.rb
  app/helpers/admin_helper.rb
  app/helpers/settings_helper.rb
  app/views/admin/_menu.html.erb
  app/views/admin/settings/_featured_settings_form.html.erb
  app/views/admin/settings/_featured_settings_table.html.erb
  app/views/admin/settings/_mixed_settings_table.html.erb
  app/views/admin/settings/_settings_table.html.erb
  app/views/admin/wizards/_header_steps.html.erb
  app/views/admin/wizards/_wizard.html.erb
  app/views/admin/wizards/index.html.erb
  app/views/admin/wizards/installer/finish.html.erb
  app/views/admin/wizards/installer/general_settings.html.erb
  app/views/admin/wizards/installer/map.html.erb
  app/views/admin/wizards/installer/new.html.erb
  app/views/admin/wizards/installer/participation_process.html.erb
  app/views/admin/wizards/installer/regional.html.erb
  app/views/admin/wizards/installer/smtp.html.erb
  app/views/layouts/wizard.html.erb
  config/i18n-tasks.yml
  config/locales/en/admin.yml
  config/locales/en/wizard.yml
  config/locales/es/admin.yml
  config/locales/es/wizard.yml
  config/routes/admin.rb
  spec/features/admin/settings_spec.rb
  spec/features/admin/wizards/installer_spec.rb
  spec/features/admin/wizards_spec.rb
  spec/helpers/settings_helper_spec.rb
Labels: Module 6
